/**
 * Fridayy - Node.js Framework Adapter
 * Discovers endpoints directly from Express / Fastify / Koa applications.
 */

import fs from 'node:fs';
import path from 'node:path';
import {
  BaseAdapter,
  AdapterScanContext,
  AdapterGenerationContext,
  AdapterExecutionContext
} from '../base.js';
import {
  FridayyToolDefinition,
  ToolExecutionResult,
  ParameterDefinition
} from '../../core/schema/types.js';
import { NodeJsScanner } from './ast-scanner.js';
import { generateToolNameFromRoute } from '../../core/tool-generator/name-sanitizer.js';
import { classifyOperation } from '../../core/permissions/classifier.js';
import { buildToolDescription } from '../../core/tool-generator/description-builder.js';
import { buildUnifiedInputSchema } from '../../core/schema/json-schema.js';
import { defaultRestExecutor } from '../rest/executor.js';
import { buildHttpRequest } from '../openapi/request-builder.js';
import { AuthenticationManager } from '../../core/authentication/manager.js';
import { defaultSecretResolver } from '../../core/authentication/secret-resolver.js';

export class NodeJsAdapter extends BaseAdapter {
  public readonly name = 'nodejs';
  public readonly description = 'Adapter for Express, Fastify, and Node.js web applications';

  private scanner = new NodeJsScanner();
  private restExecutor = defaultRestExecutor;

  public async detect(context: AdapterScanContext): Promise<{ detected: boolean; details?: any }> {
    const rootDir = context.rootDir;
    const pkgJsonPath = path.resolve(rootDir, 'package.json');

    let detectedFramework: string | undefined;
    if (fs.existsSync(pkgJsonPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf-8'));
        const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };

        if (allDeps.express) detectedFramework = 'express';
        else if (allDeps.fastify) detectedFramework = 'fastify';
        else if (allDeps.koa) detectedFramework = 'koa';
        else if (allDeps['@nestjs/core']) detectedFramework = 'nestjs';
      } catch {
        // ignore
      }
    }

    const routes = await this.scanner.scanDirectory(rootDir, 50);

    return {
      detected: Boolean(detectedFramework || routes.length > 0),
      details: {
        framework: detectedFramework || (routes.length > 0 ? 'custom' : undefined),
        discoveredRoutesCount: routes.length
      }
    };
  }

  public async generateTools(context: AdapterGenerationContext): Promise<FridayyToolDefinition[]> {
    const rootDir = context.rootDir || process.cwd();
    const routes = await this.scanner.scanDirectory(rootDir);
    const tools: FridayyToolDefinition[] = [];
    const usedToolNames = new Set<string>();

    const baseUrl =
      defaultSecretResolver.resolveBaseUrl(context.config?.source?.baseUrl) ||
      'http://localhost:3000';

    for (const r of routes) {
      let toolName = generateToolNameFromRoute(r.method, r.path);
      if (usedToolNames.has(toolName)) {
        let suffix = 2;
        while (usedToolNames.has(`${toolName}_${suffix}`)) suffix++;
        toolName = `${toolName}_${suffix}`;
      }
      usedToolNames.add(toolName);

      const pathParams: ParameterDefinition[] = r.pathParams.map(name => ({
        name,
        in: 'path',
        required: true,
        schema: { type: 'string' },
        description: `Path parameter ${name}`
      }));

      const classification = classifyOperation(
        {
          method: r.method,
          path: r.path,
          name: toolName,
          summary: r.description
        },
        context.config
      );

      const description = buildToolDescription({
        summary: r.description,
        method: r.method,
        path: r.path,
        permissionType: classification.permissions.type,
        risk: classification.risk
      });

      const inputSchema = buildUnifiedInputSchema({
        parameters: { path: pathParams }
      });

      const tool: FridayyToolDefinition = {
        id: `tool_${toolName}`,
        name: toolName,
        description,
        inputSchema,
        source: {
          type: 'nodejs',
          method: r.method,
          path: r.path,
          baseUrl
        },
        parameters: {
          path: pathParams
        },
        permissions: classification.permissions,
        risk: classification.risk,
        status: classification.status,
        metadata: {
          createdAt: new Date().toISOString(),
          autoGenerated: true,
          sourceFile: r.file,
          line: r.line
        }
      };

      tools.push(tool);
    }

    return tools;
  }

  public async executeTool(
    tool: FridayyToolDefinition,
    input: Record<string, any>,
    context: AdapterExecutionContext = {}
  ): Promise<ToolExecutionResult> {
    const authManager = new AuthenticationManager(context.config);
    const baseUrl = defaultSecretResolver.resolveBaseUrl(context.config?.source?.baseUrl);

    const preparedReq = buildHttpRequest(tool, input, baseUrl);

    if (context.headers) {
      Object.assign(preparedReq.headers, context.headers);
    }

    authManager.applyAuth(tool.authentication, {
      headers: preparedReq.headers,
      queryParams: {}
    });

    return await this.restExecutor.execute(preparedReq, tool.name, {
      timeoutMs: context.timeoutMs
    });
  }
}
