/**
 * Fridayy - Generic REST Adapter
 * Adapter for executing and declaring arbitrary REST endpoints.
 * Automatically provisions baseline operational tools when connected to an API URL.
 */

import {
  BaseAdapter,
  AdapterScanContext,
  AdapterGenerationContext,
  AdapterExecutionContext
} from '../base.js';
import {
  FridayyToolDefinition,
  ToolExecutionResult
} from '../../core/schema/types.js';
import { buildHttpRequest } from '../openapi/request-builder.js';
import { defaultRestExecutor } from './executor.js';
import { AuthenticationManager } from '../../core/authentication/manager.js';
import { defaultSecretResolver } from '../../core/authentication/secret-resolver.js';
import { buildUnifiedInputSchema } from '../../core/schema/json-schema.js';

export class RestAdapter extends BaseAdapter {
  public readonly name = 'rest';
  public readonly description = 'Adapter for REST APIs and custom HTTP endpoints';

  private restExecutor = defaultRestExecutor;

  public async detect(context: AdapterScanContext): Promise<{ detected: boolean; details?: any }> {
    const hasBaseUrl = Boolean(context.config?.source?.baseUrl || context.config?.source?.url);
    return {
      detected: hasBaseUrl,
      details: { baseUrl: context.config?.source?.baseUrl }
    };
  }

  public async generateTools(context: AdapterGenerationContext): Promise<FridayyToolDefinition[]> {
    const baseUrl =
      defaultSecretResolver.resolveBaseUrl(context.config?.source?.baseUrl || context.config?.source?.url) ||
      'http://localhost:3000';

    const tools: FridayyToolDefinition[] = [];

    // 1. Health check tool
    tools.push({
      id: 'tool_check_api_health',
      name: 'check_api_health',
      description: `Ping target API at ${baseUrl} to check availability and health status.`,
      inputSchema: buildUnifiedInputSchema({
        parameters: {
          query: [
            {
              name: 'path',
              in: 'query',
              required: false,
              schema: { type: 'string', default: '/health' },
              description: 'Health probe path (e.g. /health or /)'
            }
          ]
        }
      }),
      source: {
        type: 'rest',
        method: 'GET',
        path: '/health',
        baseUrl
      },
      permissions: {
        type: 'READ',
        read: true,
        write: false,
        destructive: false
      },
      risk: 'low',
      status: 'APPROVED',
      metadata: {
        createdAt: new Date().toISOString(),
        autoGenerated: true
      }
    });

    // 2. Dynamic REST Query Tool
    tools.push({
      id: 'tool_call_api_endpoint',
      name: 'call_api_endpoint',
      description: `Execute a structured HTTP request to the target API at ${baseUrl}.`,
      inputSchema: {
        type: 'object',
        properties: {
          path: {
            type: 'string',
            description: 'Relative endpoint path (e.g. /api/users or /products/123)'
          },
          method: {
            type: 'string',
            enum: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
            default: 'GET',
            description: 'HTTP method to execute'
          },
          queryParams: {
            type: 'object',
            description: 'Optional query parameters as key-value pairs',
            additionalProperties: true
          },
          body: {
            type: 'object',
            description: 'Optional JSON payload for POST/PUT/PATCH requests',
            additionalProperties: true
          }
        },
        required: ['path']
      },
      source: {
        type: 'rest',
        method: 'GET',
        path: '/',
        baseUrl
      },
      permissions: {
        type: 'WRITE',
        read: true,
        write: true,
        destructive: false
      },
      risk: 'medium',
      status: 'APPROVED',
      metadata: {
        createdAt: new Date().toISOString(),
        autoGenerated: true
      }
    });

    return tools;
  }

  public async executeTool(
    tool: FridayyToolDefinition,
    input: Record<string, any>,
    context: AdapterExecutionContext = {}
  ): Promise<ToolExecutionResult> {
    const authManager = new AuthenticationManager(context.config);
    const baseUrl = defaultSecretResolver.resolveBaseUrl(context.config?.source?.baseUrl);

    // If dynamic endpoint execution
    if (tool.name === 'call_api_endpoint' && input.path) {
      const dynamicTool: FridayyToolDefinition = {
        ...tool,
        source: {
          ...tool.source,
          method: input.method || 'GET',
          path: input.path.startsWith('/') ? input.path : `/${input.path}`
        }
      };

      const preparedReq = buildHttpRequest(
        dynamicTool,
        {
          ...(input.queryParams || {}),
          ...(input.body || {})
        },
        baseUrl
      );

      if (context.headers) {
        Object.assign(preparedReq.headers, context.headers);
      }

      authManager.applyAuth(tool.authentication, {
        headers: preparedReq.headers,
        queryParams: {}
      });

      return await this.restExecutor.execute(preparedReq, tool.name, {
        timeoutMs: context.timeoutMs
      });
    }

    const preparedReq = buildHttpRequest(tool, input, baseUrl);

    if (context.headers) {
      Object.assign(preparedReq.headers, context.headers);
    }

    authManager.applyAuth(tool.authentication, {
      headers: preparedReq.headers,
      queryParams: {}
    });

    return await this.restExecutor.execute(preparedReq, tool.name, {
      timeoutMs: context.timeoutMs
    });
  }
}
