/**
 * Fridayy - Laravel Framework Adapter
 * Discovers endpoints from a Laravel application's routes/*.php files and
 * executes them the same way the generic REST adapter does (Laravel is just
 * an HTTP API from the caller's point of view; no PHP runtime is needed here).
 */

import fs from 'node:fs';
import path from 'node:path';
import {
  BaseAdapter,
  AdapterScanContext,
  AdapterGenerationContext,
  AdapterExecutionContext
} from '../base.js';
import {
  FridayyToolDefinition,
  ToolExecutionResult,
  ParameterDefinition
} from '../../core/schema/types.js';
import { LaravelRouteScanner } from './route-scanner.js';
import { generateToolNameFromRoute } from '../../core/tool-generator/name-sanitizer.js';
import { classifyOperation } from '../../core/permissions/classifier.js';
import { buildToolDescription } from '../../core/tool-generator/description-builder.js';
import { buildUnifiedInputSchema } from '../../core/schema/json-schema.js';
import { defaultRestExecutor } from '../rest/executor.js';
import { buildHttpRequest } from '../openapi/request-builder.js';
import { AuthenticationManager } from '../../core/authentication/manager.js';
import { defaultSecretResolver } from '../../core/authentication/secret-resolver.js';

export class LaravelAdapter extends BaseAdapter {
  public readonly name = 'laravel';
  public readonly description = 'Adapter for Laravel PHP applications (routes/web.php, routes/api.php)';

  private scanner = new LaravelRouteScanner();
  private restExecutor = defaultRestExecutor;

  public async detect(context: AdapterScanContext): Promise<{ detected: boolean; details?: any }> {
    const rootDir = context.rootDir;
    const hasArtisan = fs.existsSync(path.join(rootDir, 'artisan'));

    let hasLaravelComposerDep = false;
    const composerPath = path.join(rootDir, 'composer.json');
    if (fs.existsSync(composerPath)) {
      try {
        const composer = JSON.parse(fs.readFileSync(composerPath, 'utf-8'));
        const allDeps = { ...composer.require, ...composer['require-dev'] };
        hasLaravelComposerDep = Boolean(allDeps['laravel/framework'] || allDeps['laravel/lumen-framework']);
      } catch {
        // ignore malformed composer.json
      }
    }

    const routes = await this.scanner.scanDirectory(rootDir, 50);

    return {
      detected: Boolean(hasArtisan || hasLaravelComposerDep || routes.length > 0),
      details: {
        framework: hasArtisan || hasLaravelComposerDep ? 'laravel' : routes.length > 0 ? 'custom-php' : undefined,
        discoveredRoutesCount: routes.length
      }
    };
  }

  public async generateTools(context: AdapterGenerationContext): Promise<FridayyToolDefinition[]> {
    const rootDir = context.rootDir || process.cwd();
    const routes = await this.scanner.scanDirectory(rootDir);
    const tools: FridayyToolDefinition[] = [];
    const usedToolNames = new Set<string>();

    // `php artisan serve` defaults to :8000, unlike the Node.js adapter's :3000.
    const baseUrl =
      defaultSecretResolver.resolveBaseUrl(context.config?.source?.baseUrl) ||
      'http://localhost:8000';

    for (const r of routes) {
      let toolName = generateToolNameFromRoute(r.method, r.path);
      if (usedToolNames.has(toolName)) {
        let suffix = 2;
        while (usedToolNames.has(`${toolName}_${suffix}`)) suffix++;
        toolName = `${toolName}_${suffix}`;
      }
      usedToolNames.add(toolName);

      const pathParams: ParameterDefinition[] = r.pathParams.map(name => ({
        name,
        in: 'path',
        required: true,
        schema: { type: 'string' },
        description: `Path parameter ${name}`
      }));

      const classification = classifyOperation(
        {
          method: r.method,
          path: r.path,
          name: toolName,
          summary: r.description
        },
        context.config
      );

      const description = buildToolDescription({
        summary: r.description,
        method: r.method,
        path: r.path,
        permissionType: classification.permissions.type,
        risk: classification.risk
      });

      const inputSchema = buildUnifiedInputSchema({
        parameters: { path: pathParams }
      });

      const tool: FridayyToolDefinition = {
        id: `tool_${toolName}`,
        name: toolName,
        description,
        inputSchema,
        source: {
          type: 'laravel',
          method: r.method,
          path: r.path,
          baseUrl
        },
        parameters: {
          path: pathParams
        },
        permissions: classification.permissions,
        risk: classification.risk,
        status: classification.status,
        metadata: {
          createdAt: new Date().toISOString(),
          autoGenerated: true,
          sourceFile: r.file,
          line: r.line,
          ...(r.controller ? { controller: r.controller } : {})
        }
      };

      tools.push(tool);
    }

    return tools;
  }

  public async executeTool(
    tool: FridayyToolDefinition,
    input: Record<string, any>,
    context: AdapterExecutionContext = {}
  ): Promise<ToolExecutionResult> {
    const authManager = new AuthenticationManager(context.config);
    const baseUrl = defaultSecretResolver.resolveBaseUrl(context.config?.source?.baseUrl);

    const preparedReq = buildHttpRequest(tool, input, baseUrl);

    if (context.headers) {
      Object.assign(preparedReq.headers, context.headers);
    }

    authManager.applyAuth(tool.authentication, {
      headers: preparedReq.headers,
      queryParams: {}
    });

    return await this.restExecutor.execute(preparedReq, tool.name, {
      timeoutMs: context.timeoutMs
    });
  }
}
