/**
 * Fridayy - Default Configuration Constants
 */

import { FridayyConfig } from '../core/schema/types.js';

export const DEFAULT_CONFIG_FILE = 'fridayy.config.json';
export const DEFAULT_TOOLS_FILE = 'fridayy.tools.json';

export const DEFAULT_CONFIG: FridayyConfig = {
  name: 'fridayy-app',
  version: '1.0.0',
  description: 'MCP Server generated by Fridayy',
  source: {
    type: 'openapi',
    path: './openapi.yaml'
  },
  server: {
    name: 'fridayy-mcp-server',
    version: '1.0.0',
    transport: 'stdio',
    port: 3000,
    host: 'localhost',
    maxRequestsPerMinute: 60
  },
  security: {
    requireApprovalForDestructive: true,
    autoApproveRead: true,
    autoApproveWrite: false,
    secretEnvPrefix: 'FRIDAYY_'
  },
  logging: {
    level: 'info',
    maskSecrets: true
  },
  tools: {
    autoGenerate: true,
    toolsFile: `./${DEFAULT_TOOLS_FILE}`
  }
};
