/**
 * Fridayy - Universal Application-to-MCP Platform
 * Core Type Definitions
 */

export type ToolPermissionType = 'READ' | 'WRITE' | 'DESTRUCTIVE';

export type ToolRiskLevel = 'low' | 'medium' | 'high';

export type ToolApprovalStatus = 'APPROVED' | 'PENDING' | 'BLOCKED' | 'REJECTED';

export type SourceType = 'openapi' | 'rest' | 'nodejs' | 'manual' | 'graphql' | string;

export type AuthType = 'apiKey' | 'bearer' | 'basic' | 'customHeader' | 'oauth2' | 'none';

export interface ParameterDefinition {
  name: string;
  in: 'path' | 'query' | 'header' | 'cookie';
  required: boolean;
  description?: string;
  schema: Record<string, any>;
  example?: any;
}

export interface RequestBodyDefinition {
  contentType: string;
  required: boolean;
  description?: string;
  schema: Record<string, any>;
  example?: any;
}

export interface ToolAuthentication {
  required: boolean;
  type?: AuthType;
  envKey?: string;
  headerName?: string;
  queryParam?: string;
  schemeName?: string;
  description?: string;
}

export interface ToolPermissions {
  type: ToolPermissionType;
  read: boolean;
  write: boolean;
  destructive: boolean;
  requiresConfirmation?: boolean;
}

export interface ToolRateLimit {
  maxRequests: number;
  windowSeconds: number;
}

export interface FridayyToolDefinition {
  id: string;
  name: string;
  description: string;
  inputSchema: {
    type: 'object';
    properties?: Record<string, any>;
    required?: string[];
    additionalProperties?: boolean;
    [key: string]: any;
  };
  outputSchema?: Record<string, any>;
  source: {
    type: SourceType;
    method?: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS' | string;
    url?: string;
    path?: string;
    baseUrl?: string;
    handler?: string;
    endpoint?: string;
    operationId?: string;
    tags?: string[];
    summary?: string;
  };
  parameters?: {
    path?: ParameterDefinition[];
    query?: ParameterDefinition[];
    header?: ParameterDefinition[];
    cookie?: ParameterDefinition[];
  };
  requestBody?: RequestBodyDefinition;
  authentication?: ToolAuthentication;
  permissions: ToolPermissions;
  risk: ToolRiskLevel;
  status: ToolApprovalStatus;
  rateLimit?: ToolRateLimit;
  metadata?: {
    createdAt?: string;
    updatedAt?: string;
    approvedAt?: string;
    approvedBy?: string;
    autoGenerated?: boolean;
    sourceFile?: string;
    [key: string]: any;
  };
}

export interface FridayyConfig {
  name: string;
  version?: string;
  description?: string;
  source: {
    type: 'openapi' | 'rest' | 'nodejs' | 'manual' | 'auto';
    path?: string;
    url?: string;
    baseUrl?: string;
    rootDir?: string;
    [key: string]: any;
  };
  server?: {
    name?: string;
    version?: string;
    transport?: 'stdio' | 'sse';
    port?: number;
    host?: string;
    maxRequestsPerMinute?: number;
    /** Name of the environment variable holding the API key required to access the SSE/HTTP transport. */
    apiKeyEnvVar?: string;
  };
  security?: {
    requireApprovalForDestructive?: boolean;
    autoApproveRead?: boolean;
    autoApproveWrite?: boolean;
    allowlist?: string[];
    denylist?: string[];
    rateLimit?: ToolRateLimit;
    secretEnvPrefix?: string;
  };
  auth?: {
    [schemeName: string]: {
      type: AuthType;
      envKey?: string;
      headerName?: string;
      queryParam?: string;
      value?: string;
    };
  };
  logging?: {
    level?: 'debug' | 'info' | 'warn' | 'error';
    auditLogPath?: string;
    maskSecrets?: boolean;
  };
  tools?: {
    autoGenerate?: boolean;
    toolsFile?: string;
    includeTags?: string[];
    excludeTags?: string[];
    includePaths?: string[];
    excludePaths?: string[];
  };
}

export interface ToolsFileStructure {
  version: string;
  generatedAt: string;
  source: string;
  tools: FridayyToolDefinition[];
}

export interface ToolExecutionResult {
  success: boolean;
  data?: any;
  error?: {
    code: string;
    message: string;
    details?: any;
  };
  metadata?: {
    statusCode?: number;
    durationMs: number;
    timestamp: string;
    toolName: string;
  };
}

export interface ScanResult {
  hasOpenApi: boolean;
  openApiFiles: string[];
  hasNodeJs: boolean;
  nodeJsFramework?: 'express' | 'fastify' | 'koa' | 'nestjs' | 'custom' | 'none';
  discoveredEndpointsCount: number;
  authSchemesDetected: string[];
  recommendedConfig: Partial<FridayyConfig>;
  details: {
    openApiSpecs?: Array<{ path: string; version: string; title: string; endpointsCount: number }>;
    routes?: Array<{ method: string; path: string; file: string; line: number }>;
  };
}
